# for running docker locally
# debian
# size: 729MB
from debian:latest
#copy docker/debian.aliyun.sources.list /etc/apt/sources.list
#copy docker/pip.conf /root/.pip/pip.conf
run apt-get update
#run apt-get -y install python3 python3-pip tesseract-ocr
run apt-get -y install autoconf python3 python3-pip tesseract-ocr
run pip3 install -r requirements.txt
workdir /app
copy example /app/example/
copy *.py *.json /app/
env PYTHONIOENCODING=utf8
ENTRYPOINT ["python3","service.py"]

